
package com.dgr.swing;

import com.dgr.attributes.ResSocConnexion;
import com.dgr.dao.DAO;
import com.dgr.dao.PersonDAO;
import com.dgr.members.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;

/**
 *
 * @author jerome.lombard
 */
public final class ListingPerson extends javax.swing.JFrame {

    /**
     * Creates new form ListingPerson
     */
    private final FenConnexion fenConnexion ;
      
    public ListingPerson(FenConnexion fenConnexion) {
        this.fenConnexion = fenConnexion;
        initComponents();
        this.addRowToJTable();       
    }

    public ArrayList listUsers(){
        ArrayList<Person> listGen = new ArrayList();
    
        for(Person user : fenConnexion.listCustomers.getListUsers()){
            listGen.add(user);
            System.out.println(user.getName());
        }
        for(Person user : fenConnexion.listEmployees.getListUsers()){
            listGen.add(user);
            System.out.println(user.getName());
        }
        return listGen;
    }
    
    public void addRowToJTable(Person newUser){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[4];
        rowData[0] = newUser.getName();
        rowData[1] = newUser.getFirst_name();
        int age = Calendar.getInstance().get(Calendar.YEAR) - newUser.getBirthYear();
        rowData[2] = age;
        rowData[3] = newUser.getClass().getSimpleName();
        model.addRow(rowData);
    }
    
    
    public void addRowToJTable(){
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DAO<Person> personDAO = new PersonDAO(ResSocConnexion.getInstance());
        ArrayList<Person> list = personDAO.findAll();
        Object rowData[] = new Object[4];
        for(int i = 0 ; i < list.size() ; i++){
            rowData[0] = list.get(i).getName();
            rowData[1] = list.get(i).getFirst_name();
            int age = Calendar.getInstance().get(Calendar.YEAR) - list.get(i).getBirthYear();
            rowData[2] = age;
            rowData[3] = list.get(i).getClass().getSimpleName();
            model.addRow(rowData);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTitle.setText("Listing des Utilisateurs :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Age", "Rôle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(2);
        }

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fenConnexion.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelTitle;
    // End of variables declaration//GEN-END:variables
}
